### ISSUE TITLE
It doesn't seem to work on my chrome browser on android phone.

### ISSUE THREAD

**Issue by dvolatility** [manki/misc-scripts#6]
Hmm, I'm wondering why my chrome browser doesn't recognize your script on my android phone.

**Comment by manki** [comment]
I presume you mean blogger-infinite-scrolling.js doesn't work on Android Chrome? I just tried opening http://blog.manki.in/?m=0 on Android Chrome; it seems to work fine for me.

**Comment by dvolatility** [comment]
Hi Manki,
Yours works. My blog's scroller works on my Chromebook, but not on my Android phone's Chrome browser for some reason. However, the scroller works on the Android's built in browser though. Here is my blog. I put the code on dropbox. http://newsmovingmarkets.com

**Comment by manki** [comment]
Strange. Your site works for me on both my Nexus 5X and Nexus 9. I have Chrome 51 on both devices. Are you running a different Chrome version?

**Comment by dvolatility** [comment]
Hey, scratch that, it works! I have no idea why it wasn't working before, or maybe I didn't notice it because of the footer. But previously my related post widget wasn't working either. I was thinking maybe it had something to do with the jquery code, which I changed. Thanks for the replies and the scroller.

**Comment by manki** [comment]
Great. I am glad the issues are all gone :)
