### ISSUE TITLE
Is there a way to get the url to change when loading more posts in Blogger?

### ISSUE THREAD

**Issue by dvolatility** [manki/misc-scripts#7]
Hi Manki,

I'm using your infinite scroller script and was wondering if I can get the url to change when loading more posts so readers can get back to the index if they leave. Thank you.

**Comment by manki** [comment]
@dvolatility: I am not sure I understand your request. Could you please elaborate a little, or maybe give an example if appropriate?

**Comment by dvolatility** [comment]
Ok, for example, I have it so your script shows a "Load More" button at the bottom of the page, and was wondering if, after being pressed, the page's url could change to reflect the older posts being shown. For example, usually when the Older Posts link is pressed it would show  http://............/search?updated-max=2017-03-01T00:06:00Z&max-results=10. That way readers can press the back button if they leave the site and get back to the older posts loaded on my blog, instead of just getting back to the homepage url.

**Comment by manki** [comment]
Oh that'd be nifty... I like that.

I think all you need to do is call `history.pushState(null, null, olderPostsLink);` right before setting `loading = false` in [line 70](https://github.com/manki/misc-scripts/blob/master/blogger-infinite-scrolling.js#L70).

But there's one problem: `olderPostsLink` is overwritten [much before](https://github.com/manki/misc-scripts/blob/master/blogger-infinite-scrolling.js#L36) we can make use of it. I'll try to fix this bug in a few days. In fact, this is already [misreporting URLs to Google Analytics](https://github.com/manki/misc-scripts/blob/master/blogger-infinite-scrolling.js#L48). You could either wait for me to fix this, or you could fix it in your code yourself.

Hope this helps. Please close this issue once you have enough information to do what you are looking to do.

**Comment by dvolatility** [comment]
Thanks. I added `history.pushState(null, null, olderPostsLink); ` right before `loading = false` as you said, but not sure what to do next.  I'm not sure what to do with those other lines with olderPostsLink.

**Comment by manki** [comment]
I have [committed a fix](https://github.com/manki/misc-scripts/commit/37ba59edf1e0073b406bf26bf96cfc4715919aa2#diff-451b6ad4beb33fa18f5530260af04cf7) for the bug I mentioned before. If you could pull in my changes, you *should* be good to go. Your browser should automatically change the URL as you load more posts. Does it do that?

**Comment by dvolatility** [comment]
It works! Wow, it's magical. Thank you so much.

**Comment by manki** [comment]
Awesome!

**Comment by dvolatility** [comment]
Dang, I have one problem with this... It has to do with the parameters that render after hitting the load more button. For example, if I press the load more button three times on the index page it loads 18 posts. But if I click a link to an outside article and then click back, I, for example, have this [url](http://politics.distressedvolatility.com/search?updated-max=2017-04-16T01:46:00-04:00&max-results=6&start=18&by-date=false), but it only shows the six posts that occurred after the 18th post on that index page. I'd like to see all of the 18 posts that loaded if possible. (This is the url that loaded: http://politics.distressedvolatility.com/search?updated-max=2017-04-16T01:46:00-04:00&max-results=6&start=18&by-date=false.)

I'm not sure what to do in that case. Do you know how to solve this issue in the code? Or, do you think it would be easier for me to just have links in posts open articles into a new window so they won't lose the posts loaded on the index page?

Thanks for your help.

**Comment by manki** [comment]
Hmm. That's technically possible, but you'll have to write some code. Basically, you'll add information about current URL, URL of the newly loaded posts, etc. to a single URL and pass it to `history.pushState`. Later, while navigating to this specially formed URL, you'll have to run some JavaScript to interpret the URL and fetch necessary older posts. I haven't done this before, and will take some learning to get this working. Unfortunately, I cannot do that right now.

To make the links open in a new window, you could do something like the following. (I haven't tested this, so it may need some tweaking before it's usable.)

    // Locate this line in your script...
    var newPosts = newDom.find(postContainerSelector).children();
    // ... and add this line right after.
    newPosts.find('a').attr('target', '_blank');

This will make links in the newly loaded posts open in a new window. Links on the original page will not be affected, however.

**Comment by dvolatility** [comment]
Great, the code above works. Thanks. Any way to tip you?

**Comment by manki** [comment]
Awesome. It's very generous of you to offer to tip—Thank you! Can I ask you to donate directly to [KDE](https://www.kde.org/community/donations/) or [Vim](http://www.vim.org/sponsor/) instead? :)
